%% 制作语义分割网络DeeplabV3+
% 定义网络输入大小，与图像大小相等.
imageSize = [400 500 3];
 
% 定义类别数量.
numClasses = numel(classes);
 
% 构建deeplabV3+.
lgraph = deeplabv3plusLayers(imageSize, numClasses, "mobilenetv2");
% lgraph = load('Deep-MbV2.mat');
% lgraph = lgraph.mb53;%mobilenet-512分辨率-3类

% 设置类别权重
imageFreq = tbl.PixelCount ./ tbl.ImagePixelCount;
classWeights = median(imageFreq) ./ imageFreq;

%% 设置训练参数

options = trainingOptions('adam', ...
    'LearnRateSchedule','piecewise',...%学习率策略，‘none’或者’piecewise’，'none’表示学习率不变，'piecewise’为分段学习率
    'LearnRateDropPeriod',10,...   %学习率下降周期
    'LearnRateDropFactor',0.4,...  %学习率下降因子
    'InitialLearnRate',1e-4, ...   %初始学习率
    'L2Regularization',0.005, ...  %L2 正则化因子
    'MaxEpochs',2, ...             %最大训练回合数
    'MiniBatchSize',6, ...         %小批量数
    'Shuffle','every-epoch', ...   %数据打乱策略，可选’once’，‘never’，‘every-epoch’；
%               ‘once’：在训练前打乱
%               ‘never’：不打乱
%               ‘every-epoch’：每个epoch打乱一次
    'VerboseFrequency',2,...       %详细频率，命令行窗口显示实时训练进程Verbose在命令行打印的频率，默认为100
    'Plots','training-progress');  %画出实时训练进程
% options = trainingOptions('adam', ...
%     'ExecutionEnvironment','gpu',...
%     'LearnRateSchedule','piecewise',...
%     'Shuffle','every-epoch', ...
%     'InitialLearnRate',0.0001, ...
%     'MaxEpochs',20, ...  
%     'MiniBatchSize',6, ...
%     'Plots','training-progress');

% options = trainingOptions('sgdm', ...
%     'LearnRateSchedule','piecewise',...
%     'LearnRateDropPeriod',10,...
%     'LearnRateDropFactor',0.3,...
%     'Momentum',0.9, ...
%     'InitialLearnRate',1e-4, ...
%     'L2Regularization',0.005, ...
%     'MaxEpochs',10, ...  
%     'MiniBatchSize',6, ...
%     'Shuffle','every-epoch', ...
%     'CheckpointPath', tempdir, ...
%     'VerboseFrequency',2,...
%     'Plots','training-progress',...
%     'ValidationPatience', 4)
% % 图像增强
augmenter = imageDataAugmenter('RandXReflection',true,...
    'RandXTranslation',[-10 10],'RandYTranslation',[-10 10]);
pximds = pixelLabelImageDatastore(imds,pxds, ...
    'DataAugmentation',augmenter);
% 训练网络
[net, info] = trainNetwork(pximds,lgraph,options);
% 保存网络
save('trainedNet.mat','net');
save('trainedInfo.mat','info');