%% 制作语义分割网络DeeplabV3+
% 定义网络输入大小，与图像大小相等.
imageSize = [400 500];
 
% 定义类别数量.
numClasses = numel(classes);
 
% 构建deeplabV3+.
lgraph = fcnLayers(imageSize, numClasses);

% 设置类别权重
imageFreq = tbl.PixelCount ./ tbl.ImagePixelCount;
classWeights = median(imageFreq) ./ imageFreq;

%% 设置训练参数

options = trainingOptions('sgdm', ...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropPeriod',10,...   %学习率下降期
    'LearnRateDropFactor',0.4,...  %学习率下降因素
    'InitialLearnRate',1e-4, ...   %初始学习率
    'L2Regularization',0.005, ...  %L2 正则化
    'MaxEpochs',2, ...            %最大时期
    'MiniBatchSize',2, ...         %小批量
    'Shuffle','every-epoch', ...   
    'VerboseFrequency',2,...       %详细频率
    'Plots','training-progress');
% options = trainingOptions('adam', ...
%     'ExecutionEnvironment','gpu',...
%     'LearnRateSchedule','piecewise',...
%     'Shuffle','every-epoch', ...
%     'InitialLearnRate',0.0001, ...
%     'MaxEpochs',20, ...  
%     'MiniBatchSize',6, ...
%     'Plots','training-progress');

% options = trainingOptions('sgdm', ...
%     'LearnRateSchedule','piecewise',...
%     'LearnRateDropPeriod',10,...
%     'LearnRateDropFactor',0.3,...
%     'Momentum',0.9, ...
%     'InitialLearnRate',1e-4, ...
%     'L2Regularization',0.005, ...
%     'MaxEpochs',10, ...  
%     'MiniBatchSize',6, ...
%     'Shuffle','every-epoch', ...
%     'CheckpointPath', tempdir, ...
%     'VerboseFrequency',2,...
%     'Plots','training-progress',...
%     'ValidationPatience', 4)
% % 图像增强
augmenter = imageDataAugmenter('RandXReflection',true,...
    'RandXTranslation',[-10 10],'RandYTranslation',[-10 10]);
pximds = pixelLabelImageDatastore(imds,pxds, ...
    'DataAugmentation',augmenter);
% 训练网络
[net, info] = trainNetwork(pximds,lgraph,options);
% 保存网络
save('trainedNet.mat','net');
save('trainedInfo.mat','info');